apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: GitRepository
metadata:
  name: web-app-manifests
  namespace: default
spec:
  interval: 1m0s
  ref:
    branch: main
  secretRef:
    name: flux-deploy-authentication
  url: https://github.com/grace303303/flux-test1/tree/main/web-app-manifests
